"""
Fiducial marker detection for answer sheet alignment.

The answer sheet PDF (generated by server.js) has four small solid black squares
in the corners of the answer area.  This module detects them, orders them as
(top-left, top-right, bottom-right, bottom-left), and returns their centroids so
the perspective correction step can warp the sheet to a known rectangle.

Detection strategy (mirrors the user-provided OpenCV script):
  1. Binarise with Otsu threshold
  2. Find external contours
  3. Keep only those whose area falls in [MIN_AREA, MAX_AREA] AND whose
     approximated polygon has exactly 4 vertices (square-like shape)
  4. Require exactly 4 such contours
  5. Order them geometrically
"""

import logging
from typing import Optional

import cv2
import numpy as np
import imutils

from omr.models import FiducialResult

logger = logging.getLogger(__name__)

# Area range (in pixels²) for fiducial squares after resizing to width=700.
# Calibrated from the user-provided script; widen slightly to be robust.
_MIN_AREA = 100
_MAX_AREA = 500

# Polygon approximation tolerance
_POLY_EPSILON = 0.04


def _order_points(pts: np.ndarray) -> np.ndarray:
    """
    Order four points as: top-left, top-right, bottom-right, bottom-left.
    Identical to the order_points() in the user-provided script.
    """
    rect = np.zeros((4, 2), dtype="float32")
    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]   # top-left: smallest sum
    rect[2] = pts[np.argmax(s)]   # bottom-right: largest sum
    diff = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(diff)]  # top-right: smallest diff
    rect[3] = pts[np.argmax(diff)]  # bottom-left: largest diff
    return rect


def _find_candidates(thresh: np.ndarray) -> list[tuple[int, int]]:
    """Return centroids of all square-ish contours within the area range."""
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)

    candidates: list[tuple[int, int]] = []
    for c in cnts:
        area = cv2.contourArea(c)
        if area < _MIN_AREA or area > _MAX_AREA:
            continue
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, _POLY_EPSILON * peri, True)
        if len(approx) != 4:
            continue
        M = cv2.moments(c)
        if M["m00"] == 0:
            continue
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
        candidates.append((cx, cy))

    return candidates


def detect_fiducials(image: np.ndarray) -> FiducialResult:
    """
    Detect the four corner fiducial markers in a BGR image.

    The image is resized to width=700 internally so that the hardcoded area
    thresholds remain valid regardless of the original capture resolution.
    Returns a FiducialResult with the ordered corner coordinates scaled back
    to the *original* image dimensions.
    """
    original_h, original_w = image.shape[:2]

    # Work at a fixed width for stable area thresholds
    resized = imutils.resize(image, width=700)
    scale_x = original_w / resized.shape[1]
    scale_y = original_h / resized.shape[0]

    gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)
    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)

    candidates = _find_candidates(thresh)

    if len(candidates) != 4:
        logger.warning("Expected 4 fiducial markers, found %d", len(candidates))

        # Second attempt: try on the raw grayscale (non-inverted)
        _, thresh2 = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
        candidates = _find_candidates(thresh2)

        if len(candidates) != 4:
            return FiducialResult(found=False, count=len(candidates))

    pts = np.array(candidates, dtype="float32")
    ordered = _order_points(pts)  # shape (4, 2) in resized space

    # Scale back to original image space
    corners = [
        [float(x * scale_x), float(y * scale_y)]
        for x, y in ordered
    ]

    return FiducialResult(found=True, count=4, corners=corners)


def draw_fiducials(image: np.ndarray, result: FiducialResult) -> np.ndarray:
    """
    Draw detected fiducial markers on a copy of the image (for debugging).
    Labels: TL, TR, BR, BL
    """
    annotated = image.copy()
    if not result.found or result.corners is None:
        return annotated

    labels = ["TL", "TR", "BR", "BL"]
    colors = [(0, 255, 0), (0, 200, 255), (0, 0, 255), (255, 100, 0)]

    for i, (corner, label, color) in enumerate(zip(result.corners, labels, colors)):
        cx, cy = int(corner[0]), int(corner[1])
        cv2.circle(annotated, (cx, cy), 8, color, -1)
        cv2.putText(annotated, label, (cx + 10, cy - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    return annotated
